micronaut:
    application:
        name: inforetrieval
    server:
        host: 192.168.1.2
        port: 8081
        cors:
            enabled: true
datasources:
    default:
        url: jdbc:postgresql://localhost:5433/info_retrieval
        username: back
        password: change.me
        driverClassName: org.postgresql.Driver
        validationQuery: SELECT 1
#        initSQL: SET search_path TO isfront
