micronaut:
    application:
        name: inforetrieval
datasources:
    default:
        url: jdbc:postgresql://localhost:5433/info_retrieval
        username: back
        password: change.me
        driverClassName: org.postgresql.Driver
        validationQuery: SELECT 1
#        initSQL: SET search_path TO isfront
